[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

# This handles the API calls
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# This handles the frontend (SPA routing)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200